/**
 * Structa Anchor program — full coverage test suite.
 *
 *   ─ Lifecycle (init → open_sale → buy → close_sale → distribute_yield
 *                → claim_yield → withdraw_principal → unlock_burn
 *                → burn_cotas → lock_burn → transfer_authority)
 *   ─ Authorisation negative tests
 *   ─ Sale-state, supply-limit and arithmetic edge cases
 *   ─ Yield distribution math + multi-holder pro-rata
 *   ─ Burn / refund pool refund mechanics
 */
import * as anchor from "@coral-xyz/anchor";
import { BN, Idl, Wallet } from "@coral-xyz/anchor";
import { TOKEN_PROGRAM_ID, getAccount } from "@solana/spl-token";
import { expect } from "chai";
import { Keypair, PublicKey } from "@solana/web3.js";

import { StructaClient, deriveProjectPdas, projectSeedFromString, deriveHolderPda } from "../sdk/src";

// IDL is generated by `anchor build` and lives at target/idl/structa.json.
// We require() it dynamically so tsc's strict mode doesn't complain when the
// file isn't present yet (e.g. on a fresh clone before the first build).
// eslint-disable-next-line @typescript-eslint/no-var-requires
const idl: Idl = require("../target/idl/structa.json");
import {
  ensureAta,
  fundUsdc,
  newFundedKeypair,
  setupUsdcMint,
  tokenBalance,
  uniqueProjectId,
  usdcUi,
} from "./helpers";

const { web3 } = anchor;

describe("structa program", () => {
  // Use the wallet/cluster supplied by `anchor test` (env).
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const programIdString = (idl as Idl).address ?? (idl as any).metadata?.address;
  const programId = new PublicKey(programIdString);
  const adminKp = (provider.wallet as Wallet).payer;

  let client: StructaClient;
  let usdcMint: PublicKey;

  before(async () => {
    client = new StructaClient({
      programId,
      connection: provider.connection,
      wallet: provider.wallet as Wallet,
      idl: idl as Idl,
    });
    usdcMint = await setupUsdcMint(provider.connection, adminKp);
  });

  // ─────────────────────────────────────────────────────────────────────
  describe("initialize_project", () => {
    it("creates project, mint and three vaults", async () => {
      const projectId = uniqueProjectId();
      const { ix } = await client.initializeProjectIx({
        authority: adminKp.publicKey,
        projectId,
        usdcMint,
        tokenDecimals: 0,
        totalSupply: 1_000,
        tokenPriceUsdc: 100_000_000n, // 100 USDC
      });
      await client.send([ix]);

      const project = await client.getProject(projectId);
      expect(project, "project state should be created").to.not.be.null;
      expect(project!.totalSupply.toNumber()).to.equal(1_000);
      expect(project!.tokenPriceUsdc.toString()).to.equal("100000000");
      expect(project!.cotasMinted.toNumber()).to.equal(0);
      expect(project!.cumulativeYieldPerToken.toString()).to.equal("0");
      expect(project!.saleOpen).to.equal(false);
      expect(project!.burnUnlocked).to.equal(false);

      // Vaults are token accounts owned by the project authority PDA.
      const pdas = client.pdas(projectId);
      const principal = await getAccount(provider.connection, pdas.vaultPrincipal);
      expect(principal.owner.equals(pdas.projectAuthority)).to.equal(true);
      expect(principal.mint.equals(usdcMint)).to.equal(true);
      const yieldVault = await getAccount(provider.connection, pdas.vaultYield);
      expect(yieldVault.amount).to.equal(0n);
      const burnVault = await getAccount(provider.connection, pdas.vaultBurn);
      expect(burnVault.amount).to.equal(0n);
    });

    it("rejects total_supply == 0", async () => {
      const projectId = uniqueProjectId();
      try {
        const { ix } = await client.initializeProjectIx({
          authority: adminKp.publicKey,
          projectId,
          usdcMint,
          tokenDecimals: 0,
          totalSupply: 0,
          tokenPriceUsdc: 1n,
        });
        await client.send([ix]);
        expect.fail("expected throw");
      } catch (err) {
        expect(String(err)).to.match(/InvalidTotalSupply/);
      }
    });

    it("rejects token_price_usdc == 0", async () => {
      const projectId = uniqueProjectId();
      try {
        const { ix } = await client.initializeProjectIx({
          authority: adminKp.publicKey,
          projectId,
          usdcMint,
          tokenDecimals: 0,
          totalSupply: 100,
          tokenPriceUsdc: 0n,
        });
        await client.send([ix]);
        expect.fail("expected throw");
      } catch (err) {
        expect(String(err)).to.match(/InvalidTokenPrice/);
      }
    });
  });

  // ─────────────────────────────────────────────────────────────────────
  describe("sale lifecycle", () => {
    let projectId: string;

    beforeEach(async () => {
      projectId = uniqueProjectId();
      const { ix } = await client.initializeProjectIx({
        authority: adminKp.publicKey,
        projectId,
        usdcMint,
        tokenDecimals: 0,
        totalSupply: 100,
        tokenPriceUsdc: 100_000_000n,
      });
      await client.send([ix]);
    });

    it("opens and closes the sale", async () => {
      await client.send([await client.openSaleIx(adminKp.publicKey, projectId)]);
      let p = await client.getProject(projectId);
      expect(p!.saleOpen).to.equal(true);

      await client.send([await client.closeSaleIx(adminKp.publicKey, projectId)]);
      p = await client.getProject(projectId);
      expect(p!.saleOpen).to.equal(false);
    });

    it("rejects open_sale if already open", async () => {
      await client.send([await client.openSaleIx(adminKp.publicKey, projectId)]);
      try {
        await client.send([await client.openSaleIx(adminKp.publicKey, projectId)]);
        expect.fail("expected throw");
      } catch (err) {
        expect(String(err)).to.match(/SaleAlreadyOpen/);
      }
    });

    it("rejects close_sale if already closed", async () => {
      try {
        await client.send([await client.closeSaleIx(adminKp.publicKey, projectId)]);
        expect.fail("expected throw");
      } catch (err) {
        expect(String(err)).to.match(/SaleAlreadyClosed/);
      }
    });

    it("rejects open_sale from non-authority", async () => {
      const stranger = await newFundedKeypair(provider.connection);
      const ix = await client.openSaleIx(stranger.publicKey, projectId);
      try {
        const tx = new web3.Transaction().add(ix);
        await provider.connection.sendTransaction(tx, [stranger]);
        expect.fail("expected throw");
      } catch (err) {
        expect(String(err)).to.match(/Unauthorized|Signature|missing required signature|0x|Error/i);
      }
    });
  });

  // ─────────────────────────────────────────────────────────────────────
  describe("buy_cotas", () => {
    let projectId: string;
    let buyer: Keypair;

    beforeEach(async () => {
      projectId = uniqueProjectId();
      const { ix } = await client.initializeProjectIx({
        authority: adminKp.publicKey,
        projectId,
        usdcMint,
        tokenDecimals: 0,
        totalSupply: 100,
        tokenPriceUsdc: 100_000_000n, // 100 USDC each
      });
      await client.send([ix]);
      await client.send([await client.openSaleIx(adminKp.publicKey, projectId)]);

      buyer = await newFundedKeypair(provider.connection);
      await fundUsdc(provider.connection, adminKp, usdcMint, buyer.publicKey, 1_000);
    });

    it("transfers USDC, mints cotas and freezes the buyer ATA", async () => {
      const { ix, buyerCotaAta } = await client.buyCotasIx({
        buyer: buyer.publicKey,
        projectId,
        usdcMint,
        amount: 3,
      });
      const tx = new web3.Transaction().add(ix);
      await provider.sendAndConfirm(tx, [buyer]);

      const cotaAcc = await getAccount(provider.connection, buyerCotaAta);
      expect(cotaAcc.amount).to.equal(3n);
      expect(cotaAcc.isFrozen).to.equal(true);

      const pdas = client.pdas(projectId);
      const principal = await getAccount(provider.connection, pdas.vaultPrincipal);
      expect(principal.amount).to.equal(BigInt(3 * 100_000_000));

      const project = await client.getProject(projectId);
      expect(project!.cotasMinted.toNumber()).to.equal(3);
    });

    it("rejects when sale is closed", async () => {
      await client.send([await client.closeSaleIx(adminKp.publicKey, projectId)]);
      const { ix } = await client.buyCotasIx({
        buyer: buyer.publicKey,
        projectId,
        usdcMint,
        amount: 1,
      });
      try {
        const tx = new web3.Transaction().add(ix);
        await provider.sendAndConfirm(tx, [buyer]);
        expect.fail("expected throw");
      } catch (err) {
        expect(String(err)).to.match(/SaleClosed/);
      }
    });

    it("rejects when buying more than total_supply", async () => {
      const { ix } = await client.buyCotasIx({
        buyer: buyer.publicKey,
        projectId,
        usdcMint,
        amount: 101,
      });
      try {
        const tx = new web3.Transaction().add(ix);
        await provider.sendAndConfirm(tx, [buyer]);
        expect.fail("expected throw");
      } catch (err) {
        expect(String(err)).to.match(/SoldOut/);
      }
    });

    it("rejects amount == 0", async () => {
      const { ix } = await client.buyCotasIx({
        buyer: buyer.publicKey,
        projectId,
        usdcMint,
        amount: 0,
      });
      try {
        const tx = new web3.Transaction().add(ix);
        await provider.sendAndConfirm(tx, [buyer]);
        expect.fail("expected throw");
      } catch (err) {
        expect(String(err)).to.match(/InvalidAmount/);
      }
    });
  });

  // ─────────────────────────────────────────────────────────────────────
  describe("yield distribution & claim (multi-holder)", () => {
    let projectId: string;
    let buyerA: Keypair;
    let buyerB: Keypair;

    beforeEach(async () => {
      projectId = uniqueProjectId();
      const { ix } = await client.initializeProjectIx({
        authority: adminKp.publicKey,
        projectId,
        usdcMint,
        tokenDecimals: 0,
        totalSupply: 1_000,
        tokenPriceUsdc: 100_000_000n,
      });
      await client.send([ix]);
      await client.send([await client.openSaleIx(adminKp.publicKey, projectId)]);

      buyerA = await newFundedKeypair(provider.connection);
      buyerB = await newFundedKeypair(provider.connection);
      await fundUsdc(provider.connection, adminKp, usdcMint, buyerA.publicKey, 10_000);
      await fundUsdc(provider.connection, adminKp, usdcMint, buyerB.publicKey, 10_000);

      const buyA = await client.buyCotasIx({
        buyer: buyerA.publicKey,
        projectId,
        usdcMint,
        amount: 4, // 40% holder
      });
      await provider.sendAndConfirm(new web3.Transaction().add(buyA.ix), [buyerA]);

      const buyB = await client.buyCotasIx({
        buyer: buyerB.publicKey,
        projectId,
        usdcMint,
        amount: 6, // 60% holder
      });
      await provider.sendAndConfirm(new web3.Transaction().add(buyB.ix), [buyerB]);
    });

    it("distributes 100 USDC pro-rata: 40 / 60", async () => {
      const pdas = client.pdas(projectId);
      // Admin tops up vault_yield with 100 USDC.
      const adminAta = await fundUsdc(provider.connection, adminKp, usdcMint, adminKp.publicKey, 0);
      // Use spl-token transfer from admin to vault_yield.
      const { transfer } = await import("@solana/spl-token");
      await transfer(
        provider.connection,
        adminKp,
        adminAta,
        pdas.vaultYield,
        adminKp,
        BigInt(100 * 10 ** 6),
      );

      const distIx = await client.distributeYieldIx({
        authority: adminKp.publicKey,
        projectId,
        amount: 100 * 10 ** 6,
      });
      await client.send([distIx]);

      const project = await client.getProject(projectId);
      expect(project!.totalYieldDistributed.toNumber()).to.equal(100 * 10 ** 6);
      // cumulative_yield_per_token = 100e6 * 1e12 / 10 = 1e19
      expect(project!.cumulativeYieldPerToken.toString()).to.equal(
        "10000000000000000000",
      );

      // Holder A claims
      const claimAIx = await client.claimYieldIx({
        holderSigner: buyerA.publicKey,
        projectId,
        usdcMint,
      });
      await provider.sendAndConfirm(new web3.Transaction().add(claimAIx), [buyerA]);
      const aAta = await ensureAta(provider.connection, adminKp, usdcMint, buyerA.publicKey);
      const aBal = await tokenBalance(provider.connection, aAta);
      // A initial = 10_000 USDC - 4*100 USDC = 9600 USDC. After yield + 40 USDC = 9640 USDC
      expect(usdcUi(aBal)).to.equal(9_640);

      // Holder B claims
      const claimBIx = await client.claimYieldIx({
        holderSigner: buyerB.publicKey,
        projectId,
        usdcMint,
      });
      await provider.sendAndConfirm(new web3.Transaction().add(claimBIx), [buyerB]);
      const bAta = await ensureAta(provider.connection, adminKp, usdcMint, buyerB.publicKey);
      const bBal = await tokenBalance(provider.connection, bAta);
      // B initial 10_000 - 6*100 = 9400 + 60 = 9460
      expect(usdcUi(bBal)).to.equal(9_460);

      const projectAfter = await client.getProject(projectId);
      expect(projectAfter!.totalYieldClaimed.toNumber()).to.equal(100 * 10 ** 6);
    });

    it("rejects claim when there's nothing to claim", async () => {
      const claimIx = await client.claimYieldIx({
        holderSigner: buyerA.publicKey,
        projectId,
        usdcMint,
      });
      try {
        await provider.sendAndConfirm(new web3.Transaction().add(claimIx), [buyerA]);
        expect.fail("expected throw");
      } catch (err) {
        expect(String(err)).to.match(/NothingToClaim/);
      }
    });

    it("rejects distribute_yield with zero amount", async () => {
      try {
        await client.send([
          await client.distributeYieldIx({
            authority: adminKp.publicKey,
            projectId,
            amount: 0,
          }),
        ]);
        expect.fail();
      } catch (err) {
        expect(String(err)).to.match(/InvalidAmount/);
      }
    });

    it("rejects distribute_yield without sufficient vault balance", async () => {
      try {
        await client.send([
          await client.distributeYieldIx({
            authority: adminKp.publicKey,
            projectId,
            amount: 1_000_000_000_000n, // 1M USDC, vault has 0
          }),
        ]);
        expect.fail();
      } catch (err) {
        expect(String(err)).to.match(/InsufficientYieldVault/);
      }
    });

    it("rejects distribute_yield with no holders", async () => {
      const projectIdEmpty = uniqueProjectId();
      const { ix } = await client.initializeProjectIx({
        authority: adminKp.publicKey,
        projectId: projectIdEmpty,
        usdcMint,
        tokenDecimals: 0,
        totalSupply: 100,
        tokenPriceUsdc: 100_000_000n,
      });
      await client.send([ix]);

      try {
        await client.send([
          await client.distributeYieldIx({
            authority: adminKp.publicKey,
            projectId: projectIdEmpty,
            amount: 1,
          }),
        ]);
        expect.fail();
      } catch (err) {
        expect(String(err)).to.match(/NoHolders/);
      }
    });
  });

  // ─────────────────────────────────────────────────────────────────────
  describe("withdraw_principal", () => {
    let projectId: string;

    beforeEach(async () => {
      projectId = uniqueProjectId();
      const { ix } = await client.initializeProjectIx({
        authority: adminKp.publicKey,
        projectId,
        usdcMint,
        tokenDecimals: 0,
        totalSupply: 50,
        tokenPriceUsdc: 100_000_000n,
      });
      await client.send([ix]);
      await client.send([await client.openSaleIx(adminKp.publicKey, projectId)]);
      const buyer = await newFundedKeypair(provider.connection);
      await fundUsdc(provider.connection, adminKp, usdcMint, buyer.publicKey, 5_000);
      const buy = await client.buyCotasIx({
        buyer: buyer.publicKey,
        projectId,
        usdcMint,
        amount: 10,
      });
      await provider.sendAndConfirm(new web3.Transaction().add(buy.ix), [buyer]);
    });

    it("authority withdraws USDC from vault_principal to a destination ATA", async () => {
      const dest = await ensureAta(provider.connection, adminKp, usdcMint, adminKp.publicKey);
      const before = await tokenBalance(provider.connection, dest);
      await client.send([
        await client.withdrawPrincipalIx({
          authority: adminKp.publicKey,
          projectId,
          destination: dest,
          amount: 500 * 10 ** 6,
        }),
      ]);
      const after = await tokenBalance(provider.connection, dest);
      expect(after - before).to.equal(BigInt(500 * 10 ** 6));
    });

    it("rejects amount > vault balance", async () => {
      const dest = await ensureAta(provider.connection, adminKp, usdcMint, adminKp.publicKey);
      try {
        await client.send([
          await client.withdrawPrincipalIx({
            authority: adminKp.publicKey,
            projectId,
            destination: dest,
            amount: 1_000_000 * 10 ** 6,
          }),
        ]);
        expect.fail();
      } catch (err) {
        expect(String(err)).to.match(/InsufficientPrincipalVault/);
      }
    });

    it("rejects when caller is not the authority", async () => {
      const stranger = await newFundedKeypair(provider.connection);
      const dest = await ensureAta(provider.connection, adminKp, usdcMint, adminKp.publicKey);
      const ix = await client.withdrawPrincipalIx({
        authority: stranger.publicKey,
        projectId,
        destination: dest,
        amount: 1,
      });
      try {
        const tx = new web3.Transaction().add(ix);
        await provider.connection.sendTransaction(tx, [stranger]);
        expect.fail();
      } catch (err) {
        expect(String(err)).to.match(/Unauthorized|missing required signature|Error/i);
      }
    });
  });

  // ─────────────────────────────────────────────────────────────────────
  describe("burn / refund pool", () => {
    let projectId: string;
    let buyer: Keypair;

    beforeEach(async () => {
      projectId = uniqueProjectId();
      const { ix } = await client.initializeProjectIx({
        authority: adminKp.publicKey,
        projectId,
        usdcMint,
        tokenDecimals: 0,
        totalSupply: 50,
        tokenPriceUsdc: 100_000_000n,
      });
      await client.send([ix]);
      await client.send([await client.openSaleIx(adminKp.publicKey, projectId)]);

      buyer = await newFundedKeypair(provider.connection);
      await fundUsdc(provider.connection, adminKp, usdcMint, buyer.publicKey, 5_000);
      const buy = await client.buyCotasIx({
        buyer: buyer.publicKey,
        projectId,
        usdcMint,
        amount: 5, // 500 USDC paid
      });
      await provider.sendAndConfirm(new web3.Transaction().add(buy.ix), [buyer]);
    });

    it("unlock_burn moves principal → burn vault and closes the sale", async () => {
      const pdas = client.pdas(projectId);
      const principalBefore = await getAccount(provider.connection, pdas.vaultPrincipal);
      expect(principalBefore.amount).to.equal(BigInt(500 * 10 ** 6));

      await client.send([await client.unlockBurnIx(adminKp.publicKey, projectId)]);

      const principalAfter = await getAccount(provider.connection, pdas.vaultPrincipal);
      expect(principalAfter.amount).to.equal(0n);
      const burn = await getAccount(provider.connection, pdas.vaultBurn);
      expect(burn.amount).to.equal(BigInt(500 * 10 ** 6));

      const project = await client.getProject(projectId);
      expect(project!.burnUnlocked).to.equal(true);
      expect(project!.saleOpen).to.equal(false);
    });

    it("burn_cotas refunds the holder at token_price_usdc and burns cotas", async () => {
      await client.send([await client.unlockBurnIx(adminKp.publicKey, projectId)]);

      const burnIx = await client.burnCotasIx({
        holderSigner: buyer.publicKey,
        projectId,
        usdcMint,
        amount: 3, // burn 3 cotas → expect 300 USDC back
      });
      await provider.sendAndConfirm(new web3.Transaction().add(burnIx), [buyer]);

      const ataUsdc = await ensureAta(provider.connection, adminKp, usdcMint, buyer.publicKey);
      const usdcBal = await tokenBalance(provider.connection, ataUsdc);
      // started with 5_000, paid 500, refunded 300 → 4_800
      expect(usdcUi(usdcBal)).to.equal(4_800);

      const pdas = client.pdas(projectId);
      const cotaAta = await ensureAta(provider.connection, adminKp, pdas.cotaMint, buyer.publicKey);
      const cotaBal = await tokenBalance(provider.connection, cotaAta);
      expect(cotaBal).to.equal(2n);

      const project = await client.getProject(projectId);
      expect(project!.cotasMinted.toNumber()).to.equal(2);

      // Holder should still be frozen since balance > 0
      const cotaAcc = await getAccount(provider.connection, cotaAta);
      expect(cotaAcc.isFrozen).to.equal(true);
    });

    it("rejects burn when burn_unlocked is false", async () => {
      const burnIx = await client.burnCotasIx({
        holderSigner: buyer.publicKey,
        projectId,
        usdcMint,
        amount: 1,
      });
      try {
        await provider.sendAndConfirm(new web3.Transaction().add(burnIx), [buyer]);
        expect.fail();
      } catch (err) {
        expect(String(err)).to.match(/BurnNotUnlocked/);
      }
    });

    it("rejects burn when holder doesn't have enough cotas", async () => {
      await client.send([await client.unlockBurnIx(adminKp.publicKey, projectId)]);
      const burnIx = await client.burnCotasIx({
        holderSigner: buyer.publicKey,
        projectId,
        usdcMint,
        amount: 999,
      });
      try {
        await provider.sendAndConfirm(new web3.Transaction().add(burnIx), [buyer]);
        expect.fail();
      } catch (err) {
        expect(String(err)).to.match(/InsufficientCotas/);
      }
    });

    it("lock_burn reverses the flag", async () => {
      await client.send([await client.unlockBurnIx(adminKp.publicKey, projectId)]);
      await client.send([await client.lockBurnIx(adminKp.publicKey, projectId)]);
      const project = await client.getProject(projectId);
      expect(project!.burnUnlocked).to.equal(false);
    });

    it("rejects lock_burn when not unlocked", async () => {
      try {
        await client.send([await client.lockBurnIx(adminKp.publicKey, projectId)]);
        expect.fail();
      } catch (err) {
        expect(String(err)).to.match(/BurnAlreadyLocked/);
      }
    });
  });

  // ─────────────────────────────────────────────────────────────────────
  describe("transfer_authority", () => {
    it("authority can transfer control to another wallet", async () => {
      const projectId = uniqueProjectId();
      const { ix } = await client.initializeProjectIx({
        authority: adminKp.publicKey,
        projectId,
        usdcMint,
        tokenDecimals: 0,
        totalSupply: 100,
        tokenPriceUsdc: 100_000_000n,
      });
      await client.send([ix]);
      const newAuthority = Keypair.generate();
      await client.send([
        await client.transferAuthorityIx({
          authority: adminKp.publicKey,
          projectId,
          newAuthority: newAuthority.publicKey,
        }),
      ]);
      const project = await client.getProject(projectId);
      expect(project!.authority.toBase58()).to.equal(newAuthority.publicKey.toBase58());
    });

    it("rejects transfer with default Pubkey", async () => {
      const projectId = uniqueProjectId();
      const { ix } = await client.initializeProjectIx({
        authority: adminKp.publicKey,
        projectId,
        usdcMint,
        tokenDecimals: 0,
        totalSupply: 100,
        tokenPriceUsdc: 100_000_000n,
      });
      await client.send([ix]);
      try {
        await client.send([
          await client.transferAuthorityIx({
            authority: adminKp.publicKey,
            projectId,
            newAuthority: PublicKey.default,
          }),
        ]);
        expect.fail();
      } catch (err) {
        expect(String(err)).to.match(/InvalidAuthority/);
      }
    });
  });

  // ─────────────────────────────────────────────────────────────────────
  describe("PDA derivation parity", () => {
    it("client-derived PDAs match what the program expects", async () => {
      const projectId = uniqueProjectId();
      const seed = projectSeedFromString(projectId);
      const expected = deriveProjectPdas(programId, seed);
      const actual = client.pdas(projectId);
      expect(actual.project.toBase58()).to.equal(expected.project.toBase58());
      expect(actual.cotaMint.toBase58()).to.equal(expected.cotaMint.toBase58());
      expect(actual.vaultPrincipal.toBase58()).to.equal(expected.vaultPrincipal.toBase58());
      expect(actual.vaultYield.toBase58()).to.equal(expected.vaultYield.toBase58());
      expect(actual.vaultBurn.toBase58()).to.equal(expected.vaultBurn.toBase58());
    });

    it("holder PDA is deterministic", () => {
      const wallet = Keypair.generate().publicKey;
      const projectId = uniqueProjectId();
      const a = client.holder(projectId, wallet);
      const b = deriveHolderPda(programId, client.pdas(projectId).project, wallet);
      expect(a.address.toBase58()).to.equal(b.address.toBase58());
    });
  });
});
